#import "VBSSliceExecutor.h"
#import "VBSGGUF.h"
#import "VBSMetal.h"

@interface VBSSliceExecutor(){VBSGGUFModel*_model;VBSMetalCompiler*_compiler;id<MTLBuffer>_stage[2],_private[2];id<MTLCommandBuffer>_inflight[2];NSUInteger _turn;}@end
@implementation VBSSliceExecutor
- (instancetype)initWithModel:(VBSGGUFModel*)m compiler:(VBSMetalCompiler*)c windowBytes:(NSUInteger)b{if((self=[super init])){_model=m;_compiler=c;_windowBytes=MAX(b,4096);for(int i=0;i<2;i++){_stage[i]=[c.device newBufferWithLength:_windowBytes options:MTLResourceStorageModeShared];_private[i]=[c.device newBufferWithLength:_windowBytes options:MTLResourceStorageModePrivate];}if(!_stage[0]||!_stage[1]||!_private[0]||!_private[1])return nil;}return self;}
- (BOOL)runLinearTensor:(VBSTensor*)t input:(id<MTLBuffer>)x output:(id<MTLBuffer>)y error:(NSError**)error{VBSBlockGeometry g;if(!VBSGeometryForType(t.type,&g))return NO;if(x.length<t.columns*sizeof(float)||y.length<t.rows*sizeof(float)){if(error)*error=[NSError errorWithDomain:@"Verum.Slice" code:1 userInfo:@{NSLocalizedDescriptionKey:@"Activation buffer is smaller than tensor dimensions"}];return NO;}uint64_t maxBlocks=_windowBytes/g.bytesPerBlock;if(!maxBlocks){return NO;}uint64_t colQuantum=g.elementsPerBlock;uint64_t maxCols=MAX(colQuantum,(maxBlocks/MAX((uint64_t)1,t.rows))*colQuantum);maxCols=MIN(maxCols,(uint64_t)UINT32_MAX-(UINT32_MAX%colQuantum));if(maxCols>t.columns)maxCols=t.columns-(t.columns%colQuantum);if(!maxCols)maxCols=colQuantum;
    id<MTLComputePipelineState>p=[_compiler linearPipelineForType:t.type error:error];if(!p)return NO;BOOL first=YES;
    for(uint64_t cs=0;cs<t.columns;){uint64_t cc=MIN(maxCols,t.columns-cs);cc-=cc%colQuantum;if(!cc)cc=colQuantum;uint64_t packedRow=(cc/colQuantum)*g.bytesPerBlock;uint64_t maxRows=MIN(_windowBytes/packedRow,(uint64_t)UINT32_MAX);for(uint64_t rs=0;rs<t.rows;){uint64_t rc=MIN(maxRows,t.rows-rs);NSUInteger slot=(_turn++)&1,copied=0;if(_inflight[slot]){[_inflight[slot] waitUntilCompleted];if(_inflight[slot].status==MTLCommandBufferStatusError){if(error)*error=_inflight[slot].error;return NO;}_inflight[slot]=nil;}if(![_model copyPackedTileOfTensor:t rowStart:rs rowCount:rc columnStart:cs columnCount:cc destination:_stage[slot].contents capacity:_windowBytes bytesCopied:&copied error:error])return NO;id<MTLCommandBuffer>cb=[_compiler.queue commandBuffer];id<MTLBlitCommandEncoder>b=[cb blitCommandEncoder];[b copyFromBuffer:_stage[slot] sourceOffset:0 toBuffer:_private[slot] destinationOffset:0 size:copied];[b endEncoding];id<MTLComputeCommandEncoder>e=[cb computeCommandEncoder];[e setComputePipelineState:p];[e setBuffer:_private[slot] offset:0 atIndex:0];[e setBuffer:x offset:cs*sizeof(float) atIndex:1];[e setBuffer:y offset:rs*sizeof(float) atIndex:2];uint32_t n=(uint32_t)cc,rows=(uint32_t)rc,add=first?0:1;[e setBytes:&n length:4 atIndex:3];[e setBytes:&rows length:4 atIndex:4];[e setBytes:&add length:4 atIndex:5];NSUInteger w=MIN(p.maxTotalThreadsPerThreadgroup,256u);[e dispatchThreads:MTLSizeMake(rc,1,1) threadsPerThreadgroup:MTLSizeMake(w,1,1)];[e endEncoding];[cb commit];_inflight[slot]=cb;rs+=rc;}first=NO;cs+=cc;}
    for(int i=0;i<2;i++)if(_inflight[i]){[_inflight[i] waitUntilCompleted];if(_inflight[i].status==MTLCommandBufferStatusError){if(error)*error=_inflight[i].error;return NO;}_inflight[i]=nil;}return YES;}
@end
